### PR TITLE
Add CMake option to disable static library

### PR DESCRIPTION
**Pull request by cicku**
This patch let packagers determine if they need static library or not, it will notably save the space if static library is not needed.

### CODE REVIEW

**Comment by andrewrk** [comment]
Isn't there a cmake generic way to do this without complicating CMakeLists.txt?

**Comment by cicku** [comment]
-DBUILD_STATIC_LIBS=OFF?

i'm not sure if it works, can only test this tomorrow.

**Comment by cicku** [comment]
I may find a better way to do this, please wait for my updated patch tomorrow(its pretty late here right now).

**Comment by cicku** [comment]
Hmm...

I tried various ways, and read CMake docs again and again, and the result is, no official CMake variable to disable static library, like BUILD_STATIC_LIBS(opposite of BUILD_SHARED_LIBS which is included in CMake). I've searched projects I'm familiar with to see if there are any new CMake enhancements, like [OpenCV's CL file](https://github.com/Itseez/opencv/blob/master/CMakeLists.txt), [RUCE's CL file](https://github.com/Rocaloid/RUCE/blob/master/CMakeLists.txt), [jsoncpp's CL file](https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/CMakeLists.txt) and !%@#... But I didn't see any macros from CMake. Apparently controls are still from downstream, and they all contain stuffs more than my patch just because libebur is a small library, these examples above are huge. CMake upstream said that they don't mandate any conventions from projects, thus building static libs is still handled by downstream CMakeLists.txt instead of CMake internal.

My final opinion here is, keep my first patch as-is. Let users demand to build static or not. If you like to see an option for shared lib as well since some system don't prefer shared libs, I can add this, but complicating the CL files can't be avoided... :joy:

**Comment by andrewrk** [comment]
Hmm makes sense. I'll give a week or so to see if @jiixyj has an opinion on this, then I'll merge the pull request.

**Comment by cicku** [comment]
This PR has been obsoleted by pull request #35 , however since #35 does more, you can choose to decide which goes first.

Thank you in advance!

**Pull request merged**
