### PR TITLE
Versioned dlls and corrected dll installation on MinGW

### PR DESCRIPTION
**Pull request by Adsun701**
This enables `.dll` versioning when using MinGW, and corrects installation of `.dll` files into the `bin` directory instead of the `lib` directory.

### CODE REVIEW

**Comment by jiixyj** [comment]
The install part looks good to me. The MinGW part I'm not sure yet -- how does the name of the Windows DLL look right now? How does Visual Studio name the DLL? Should they be the same or follow MinGW DLLs some other naming scheme?

**Comment by jiixyj** [comment]
Maybe `if(WIN32)` instead of `if(MINGW)` would be enough to make the behavior consistent between Windows compilers?

**Comment by Adsun701** [comment]
@jiixyj Fixed.

**Comment by Adsun701** [comment]
@jiixyj Both MinGW and Visual Studio should use the same versioning scheme, ideally to avoid breaking changes between major versions.

**Comment by Adsun701** [comment]
@jiixyj Is this ready to be merged?

**Comment by jiixyj** [comment]
Sure, thanks for the reminder!

**Comment by Be-ing** [comment]
I think this broke DLL builds with MSVC.

**Comment by Be-ing** [comment]
Building dynamically with MSVC has this error:
```
   Creating library ebur128.lib and object ebur128.exp
ebur128.exp : warning LNK4070: /OUT:EBUR128.dll directive in .EXP differs from output filename 'ebur128-1.dll'; ignoring directive
```

**Comment by Be-ing** [comment]
Fix is in #110.

**Pull request merged**
